/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.athletica.crm.api.schemas


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param fullName 
 * @param phone 
 */
@Serializable
data class AddCustomerRequest (

    @SerialName(value = "fullName")
    val fullName: String,

    @SerialName(value = "phone")
    val phone: String? = null

) {


}

