/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.athletica.crm.api.schemas

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

/**
 * 
 *
 * @param totalCount Всего записей
 * @param hasMore Есть ли еще клиенты
 * @param customers 
 */
@Serializable

data class CustomerListResponse (

    /* Всего записей */
    @SerialName(value = "totalCount")
    val totalCount: Int,

    /* Есть ли еще клиенты */
    @SerialName(value = "hasMore")
    val hasMore: Boolean,

    @SerialName(value = "customers")
    val customers: List<CustomerInList>

) {


}

