/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package ru.athletica.crm.api.schemas


import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.Contextual

/**
 * 
 *
 * @param key 
 * @param `value` 
 */
@Serializable

data class UserSetting (

    @SerialName(value = "key")
    val key: String,

    @Contextual @SerialName(value = "value")
    val `value`: Any

) {


}

